// Code generated by protoc-gen-go-grpcadapter. DO NOT EDIT.
// source: gorpc/service.proto

package gorpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ExampleServiceAdapter is the server API for ExampleService service.
// for forward compatibility
type ExampleServiceAdapter struct {
	srv ExampleServiceServer
	cc  grpc.ClientConnInterface
}

func NewExampleServiceAdapter(srv ExampleServiceServer) ExampleServiceClient {
	return &ExampleServiceAdapter{
		srv: srv,
	}
}

func (a *ExampleServiceAdapter) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	return a.srv.Echo(ctx, in)
}

func (a *ExampleServiceAdapter) EchoStream(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (ExampleService_EchoStreamClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoStream not implemented")
}
