// Code generated by protoc-gen-go-grpcadapter. DO NOT EDIT.
// source: gorpc/service.proto

package gorpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// ExampleAdapter is the server API for Example service.
// for forward compatibility
type ExampleAdapter struct {
	srv ExampleServer
	cc  grpc.ClientConnInterface
}

func NewExampleAdapter(srv ExampleServer) ExampleClient {
	return &ExampleAdapter{
		srv: srv,
	}
}

func (a *ExampleAdapter) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	return a.srv.Echo(ctx, in)
}

func (a *ExampleAdapter) EchoStream(ctx context.Context, opts ...grpc.CallOption) (Example_EchoStreamClient, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EchoStream not implemented")
}
